name: Checking & fixing php style

on:
  push:
    branches:
      - 'admin-auth'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/admin-auth'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling